### ISSUE TITLE
Cannot go from having a policy document to not having one

### ISSUE THREAD

**Issue by devops-flipsidecrypto** [cloudposse/terraform-aws-iam-role#48] opened 2022-07-20 18:24 UTC
## Describe the Bug

When removing the only custom policy document on an applied role where previously a custom policy is set it is impossible to get Terraform to a state where it can delete the custom policy:

```
│ Error: while setting policy (), encountered: Error parsing policy: Unknown error parsing statement
│
│   with module.vpn-server-Transit.module.vpn-server-role.aws_iam_policy.default[0],
│   on .terraform/modules/vpn-server-Transit.vpn-server-role/main.tf line 45, in resource "aws_iam_policy" "default":
│   45: resource "aws_iam_policy" "default" {
```

## Expected Behavior

Since the number of policy documents was set to zero I would expect to be able to cleanly detach and delete the custom IAM policy leaving only managed policy ARNs

## Steps to Reproduce

With a Terraform file:

```
data "aws_iam_policy_document" "vpn-server" {
  statement {
    actions = [
      "ec2:Describe*",
      "ec2:CreateRoute",
      "ec2:ReplaceRoute",
      "ec2:DeleteRoute",
      "cloudwatch:PutMetricData",
    ]

    resources = ["*"]
  }

  statement {
    actions = [
      "route53:ChangeResourceRecordSets",
    ]

    resources = [
      "arn:aws:route53:::hostedzone/${local.zone_id}/*",
    ]
  }

  statement {
    actions = [
      "route53:List*",
    ]

    resources = [
      "*",
    ]
  }
}

module "vpn-server-role" {
  source = "cloudposse/iam-role/aws"
  version     = "v0.16.2"

  policy_description = "VPN server access"
  role_description   = "VPN server access"

  principals = {
    Service =  [
      "ec2.amazonaws.com",
      "ssm.amazonaws.com",
    ]
  }

  managed_policy_arns = formatlist("arn:aws:iam::aws:policy/%s", [
    "AmazonSSMManagedInstanceCore",
  ])

  policy_documents = [
    data.aws_iam_policy_document.vpn-server.json,
  ]

  instance_profile_enabled = true

  context = var.context
}
```

Apply and create the role. A policy will also be created and attached to the role.

Now revise to the following:

```
module "vpn-server-role" {
  source = "cloudposse/iam-role/aws"
  version     = "v0.16.2"

  policy_description = "VPN server access"
  role_description   = "VPN server access"

  principals = {
    Service =  [
      "ec2.amazonaws.com",
      "ssm.amazonaws.com",
    ]
  }

  managed_policy_arns = formatlist("arn:aws:iam::aws:policy/%s", [
    "AmazonSSMManagedInstanceCore",
    "CloudWatchAgentAdminPolicy",
    "AmazonVPCFullAccess",
    "AmazonRoute53FullAccess",
  ])

  policy_document_count = 0
  
  instance_profile_enabled = true

  context = var.context
}
```

And you'll find that applying produces the above error.

## Environment

 - OS: MacOS 12.4
 - Version: Terraform v1.2.4

## Additional Context

Requires that the role be existing ahead of time, e.g. is only applicable on change operations

**Comment by arichtman** [comment] 2022-11-16 03:49
I had the same issue. We worked around it by destroying and reapplying with a dummy policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "none:null",
            "Resource": "*"
        }
    ]
}
```

**Comment by Nuru** [comment] 2023-06-14 20:32
Closing this as "invalid" because I cannot reproduce it. Below is how I tried to reproduce it. If I missed something, you may reopen this issue with an explanation of what I missed:

<details><summary>Terraform code (click to reveal)</summary>

```hcl
provider "aws" {
  region = "us-east-2"
}

variable "policy" {
  type        = bool
  description = "Set 'true' to use inline policy"
  default     = true
}

data "aws_iam_policy_document" "vpn-server" {
  statement {
    actions = [
      "ec2:Describe*",
      "ec2:CreateRoute",
      "ec2:ReplaceRoute",
      "ec2:DeleteRoute",
      "cloudwatch:PutMetricData",
    ]

    resources = ["*"]
  }

  statement {
    actions   = ["route53:ChangeResourceRecordSets"]
    resources = ["*"]
  }

  statement {
    actions   = ["route53:List*"]
    resources = ["*"]
  }
}

module "vpn-server-role" {
  source  = "cloudposse/iam-role/aws"
  version = "v0.16.2"

  policy_description = "VPN server access"
  role_description   = "VPN server access"

  principals = {
    Service = [
      "ec2.amazonaws.com",
      "ssm.amazonaws.com",
    ]
  }

  managed_policy_arns = formatlist("arn:aws:iam::aws:policy/%s", var.policy ? [
    "AmazonSSMManagedInstanceCore",
    ] : [
    "AmazonSSMManagedInstanceCore",
    "CloudWatchAgentAdminPolicy",
    "AmazonVPCFullAccess",
    "AmazonRoute53FullAccess",
  ])

  policy_documents = var.policy ? [
    data.aws_iam_policy_document.vpn-server.json,
  ] : []
  policy_document_count = var.policy ? 1 : 0

  instance_profile_enabled = true

  name = "eg-iam-role-bug-test"
}
```

</details>

I then ran these commands, and they all worked fine:

```
terraform init
terraform apply -var policy=true
terraform apply -var policy=false
terraform apply -var policy=true
terraform destroy
```

**Closed by Nuru** 2023-06-14 20:32 UTC
Labels: bug
